### PR TITLE
Fix `--system-site-packages` for `upgrade --install`

### LINKED ISSUE #1344: `pipx upgrade --install` ignores `--system-site-packages` option
**Describe the bug**

Recently in [this PR](https://github.com/pypa/pipx/pull/1267) the `--install` option was added to the `upgrade` command.
Unfortunately this doesn't seem to respect the `--system-site-packages` option.

**How to reproduce**

When using `upgrade --install` the `--system-site-packages` option isn't respected:
```sh
❯ pipx upgrade --install --system-site-packages pycowsay
❯ grep system $HOME/.local/share/pipx/venvs/pycowsay/pyvenv.cfg
include-system-site-packages = false
```

Comparison with the `install` command, where it works correctly:
```sh
❯ pipx install --system-site-packages pycowsay
❯ grep system $HOME/.local/share/pipx/venvs/pycowsay/pyvenv.cfg
include-system-site-packages = true
command = /usr/bin/python3 -m venv --without-pip --system-site-packages /home/sadamczyk/.local/share/pipx/venvs/pycowsay
```

**Expected behavior**

The `upgrade --install` command should handle the `--system-site-packages` option just like the `install` command does.

**Investigation**

Looking through the code, the `--system-site-packages` option seems to be passed to the `install` command in the `venv_args` variable from the `get_venv_args` function: https://github.com/pypa/pipx/blob/5482fac6c3dfc3775af398d630ef30102f15bdcc/src/pipx/main.py#L170-L174
https://github.com/pypa/pipx/blob/5482fac6c3dfc3775af398d630ef30102f15bdcc/src/pipx/main.py#L182

But `venv_args` is only passed to the `run`, `install` and `install-all` commands
https://github.com/pypa/pipx/blob/5482fac6c3dfc3775af398d630ef30102f15bdcc/src/pipx/main.py#L244-L253
... but not to the `upgrade` command:
https://github.com/pypa/pipx/blob/5482fac6c3dfc3775af398d630ef30102f15bdcc/src/pipx/main.py#L294-L304

It might be enough to add the required function arguments so that the `venv_args` from the main.py can be passed through all the way to the `install` call here:
https://github.com/pypa/pipx/blob/5482fac6c3dfc3775af398d630ef30102f15bdcc/src/pipx/commands/upgrade.py#L111-L114

### PR DESCRIPTION
**Pull request by sadamczyk**
Fix #1344

- [x] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes

The `--system-site-package` option currently doesn't do anything when used with `upgrade --install`.
This PR adds `venv_args` to the upgrade command so that it can be passed through to the install command, when the `--install` option is set.

## Test plan

Tested by running

```
pipx upgrade --install --system-site-packages pycowsay
grep system $HOME/.local/share/pipx/venvs/pycowsay/pyvenv.cfg
```

Before the PR this returns:
```
include-system-site-packages = false
```

After applying the PR it returns:
```
include-system-site-packages = true
command = /usr/bin/python3.12 -m venv --without-pip --system-site-packages /home/sadamczyk/.local/share/pipx/venvs/pycowsay
```

Also successfully tested by installing https://github.com/essembeh/gnome-extensions-cli which requires the system site packages to work for the `--dbus` integration. Before this ran into an error because of the missing required 
system dependencies.
```
pipx upgrade --install --system-site-packages gnome-extensions-cli
gext --dbus update --install -y nightthemeswitcher@romainvigier.fr
```

### CODE REVIEW

File: changelog.d/1344.bugfix.md [hunk 1]
```diff
@@ -0,0 +1 @@
+Make the --system-site-packages option actually work with upgrade --install
```
Comment (chrysle) [inline changelog.d/1344.bugfix.md:1]:
```suggestion
Make the Python `venv` module arguments work with `upgrade --install`
```

**Review by chrysle — APPROVED** [review]

**Comment by chrysle** [comment]
Thanks!
